name: Generate README PDFs

on:
  release:
    types: [published] # Run when a release is published
  workflow_dispatch: # Allow manual trigger from Actions tab

permissions:
  contents: write # Needed to upload release assets

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install pandoc & wkhtmltopdf
        run: sudo apt-get update && sudo apt-get install -y pandoc wkhtmltopdf

      - name: Convert all README.md files to PDFs
        run: |
          mkdir -p pdfs
          for file in $(find . -name "README.md"); do
            # Create a safe filename based on folder name
            folder=$(basename $(dirname "$file"))
            [ "$folder" = "." ] && folder="root"
            pandoc "$file" -o "pdfs/${folder}_README.pdf" --pdf-engine=wkhtmltopdf
          done

      - name: Upload PDFs to GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          files: pdfs/*.pdf
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
