name: Convert README.md Files to PDFs

on:
  release:
    types: [published]
  workflow_dispatch:

permissions:
  contents: write # Required to upload release assets

jobs:
  convert:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install Pandoc and wkhtmltopdf
        run: |
          sudo apt-get update
          sudo apt-get install -y pandoc wkhtmltopdf

      - name: Convert README.md Files to PDFs
        run: |
          mkdir -p pdfs
          i=1
          # Find all README.md files, sort them, and convert each to a PDF
          find . -type f -iname "README.md" | sort | while read file; do
            # Generate output PDF file name based on sequence
            out="pdfs/${i}.pdf"
            echo "Converting $file to $out"
            pandoc "$file" -o "$out" --pdf-engine=wkhtmltopdf
            i=$((i+1))
          done

      - name: Upload PDFs to Release
        uses: softprops/action-gh-release@v1
        with:
          files: pdfs/*.pdf
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
